name = "play-tichu-worker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-29"
usage_model = "bundled"

[build]
command = "npm install && npm test && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "rooms", class_name = "GameRoom"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["GameRoom"]
